#version 430

layout (location = 0, r32f) uniform readonly image2D rtao;
layout (location = 1, rgba32f) uniform image2D outp;

layout (local_size_x = 2, local_size_y = 2, local_size_z = 1) in;

void main() {

    ivec2 dtID = ivec2(gl_GlobalInvocationID);
    vec4 c1 = imageLoad(outp, dtID);
    float t = imageLoad(rtao, dtID).x * 0.1f;
    vec4 c2 = vec4(t, t, t, 1.0f);
    vec4 cFinal = c1 * 0.9f + c2;

    imageStore(outp, dtID, cFinal);
}